steps:
  # Configure a kubectl workspace for this project
  - name: gcr.io/cloud-builders/kubectl
    args:
      - kafka
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_CUSTOM_ZONE
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
  # Deploy with Helm
  - name: gcr.io/my-second-project/helm
    args:
      - repo
      - add
      - strimzi
      - https://strimzi.io/charts/
    #env:
      #- KUBECONFIG=/workspace/.kube/config
      #- TILLERLESS=false
      #- TILLER_NAMESPACE=kube-system
  - name: gcr.io/my-second-project/helm
    args:
      - repo
      - update
    #env:
      #- KUBECONFIG=/workspace/.kube/config
  - name: gcr.io/my-second-project/helm
    args:
      - install
      - strimzi
      - strimzi/strimzi-kafka-operator
      - -namespace
      - kafka
    #env:
      #- KUBECONFIG=/workspace/.kube/config
  - name: gcr.io/cloud-builders/kubectl
    args:
      - apply
      - -f
      - kafka.yaml 
      - -n 
      - kafka
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_CUSTOM_ZONE
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
timeout: 1200s
substitutions:
  _CUSTOM_ZONE: us-central1-c
  _CUSTOM_CLUSTER: cluster-1